### ISSUE TITLE
PubSubLite Client No Longer Working With Service Account JSON File

### ISSUE THREAD

**Issue by tristeybro** [googleapis/python-pubsublite#269] opened 2021-11-02 14:30 UTC
Hello,

I very recently (in the past day or so) started receiving the following error when trying to using the PubSubLite client with my service account json file:

ERROR AuthMetadataPluginCallback "<google.auth.transport.grpc.AuthMetadataPlugin object at 0x10ec5d0a0>" raised exception!
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/grpc/_plugin_wrapping.py", line 89, in __call__
    self._metadata_plugin(
  File "/usr/local/lib/python3.9/site-packages/google/auth/transport/grpc.py", line 97, in __call__
    callback(self._get_authorization_headers(context), None)
  File "/usr/local/lib/python3.9/site-packages/google/auth/transport/grpc.py", line 83, in _get_authorization_headers
    self._credentials.before_request(
  File "/usr/local/lib/python3.9/site-packages/google/auth/credentials.py", line 131, in before_request
    self.apply(headers)
  File "/usr/local/lib/python3.9/site-packages/google/auth/credentials.py", line 107, in apply
    _helpers.from_bytes(token or self.token)
  File "/usr/local/lib/python3.9/site-packages/google/auth/_helpers.py", line 121, in from_bytes
    raise ValueError("{0!r} could not be converted to unicode".format(value))
ValueError: None could not be converted to unicode

### Code to Reproduce:

```
import json
import os
from google.cloud.pubsublite.types import (
    CloudRegion,
    CloudZone,
    MessageMetadata,
    TopicPath,
)
from google.oauth2 import service_account
from google.cloud.pubsublite.cloudpubsub import PublisherClient

project_number = ...
cloud_region = ...
zone_id = ...
topic_id = ...
cloud_region = CloudRegion(cloud_region)
cloud_zone = CloudZone(cloud_region, zone_id)
topic_path = "TopicPath(project_number, cloud_zone, topic_id)
service_account_file = os.getenv("GOOGLE_APPLICATION_CREDENTIALS")
credentials = service_account.Credentials.from_service_account_file(service_account_file)
with PublisherClient(credentials=credentials) as publisher_client:
    message = json.dumps({"blah": 1}).encode("utf-8")
    publisher_client.publish(topic_path, message)
```

#### Environment details

  - OS type and version:
  - Python version: 3.9.1
  - pip version: 20.3.3
  - `google-cloud-pubsublite` version: 1.1.1

What is the fix or workaround here? This code had been working correctly for a long time and only recently within the last day or so began to fail. I created a new service account JSON file from scratch as a sanity check, but that too produced the same error.

**Comment by meredithslota** [comment] 2021-11-13 23:59
Marking this as a bug since it seems to be a change in behavior but I have not looked into it fully yet.

**Comment by anguillanneuf** [comment] 2022-01-11 22:31
@tristeybro Your code ran for me in - 

- Python version: 3.9
- pip version: 21.3.1
- google-cloud-pubsublite version: both 1.1.1 and 1.2.0

The error looks like an auth issue. Can you check the roles on your service account? 

`gcloud asset search-all-iam-policies --query="policy:{your-service-account-id}@{your-project}.iam.gserviceaccount.com"`

**Comment by anguillanneuf** [comment] 2022-01-13 19:23
@tristeybro Feel free to re-open if you are still having issues. I couldn't reproduce your error.

**Closed by anguillanneuf** 2022-01-13 19:23 UTC
Labels: type: bug, priority: p2, api: pubsublite
